/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'spain' at '30/04/17 18:45' with Gradle 2.14.1
 *
 * @author spain, @date 30/04/17 18:45
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
